### ISSUE TITLE
Remove hardcoded T0/T1 testnet pool from methods 

### ISSUE THREAD

**Issue by ndeporzio** [panoptic-labs/market_maker_bot#14]
**Feature Suggestion**

Some methods are defined with the testnet T0/T1 token pool PanopticPool address as a parameter that users can't adjust. For mainnet operations, pools for any token pair need to be specifiable. Update these methods so that they can be applied to generic token pools.

**Comment by flanagansteve** [comment]
Further: Remove any hard-coded references to a specific pool. And alter some methods such as [panopticish.collateralToken1](https://github.com/panoptic-labs/market_maker_bot/blob/0367d8410bfcdd450b90dbbbd2203c44d7ae5518/src/connectors/panoptic/panoptic.ts#L379) which just call .collateralToken1 on the config.panopticPool, when it should instead accept panoptic pool as an argument.
